# Generated by Django 3.2.9 on 2022-02-03 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='wish',
            field=models.BooleanField(default=True),
        ),
    ]
