# Generated by Django 3.2.9 on 2022-02-03 23:51

from django.db import migrations, models
import enum


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_wish_wish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='wish',
            field=models.BooleanField(verbose_name=enum.unique),
        ),
    ]
