# Generated by Django 3.2.9 on 2022-02-06 12:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bid_count',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='listing',
            name='bid_max',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='wish',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 9, 13, 45, 450537)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 9, 13, 45, 447538)),
        ),
    ]
