# Generated by Django 3.2.9 on 2022-02-06 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20220206_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='created',
        ),
        migrations.AddField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 9, 14, 48, 158446)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 9, 14, 48, 157447)),
        ),
    ]
