# Generated by Django 3.2.9 on 2022-02-06 17:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20220206_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 17, 27, 46, 774439, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='bid_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 17, 27, 46, 773438, tzinfo=utc)),
        ),
    ]
